### ISSUE TITLE
"Build" or "deploy" activities not documented?

### ISSUE THREAD

**Issue by dfsklar** [michaelcfine/karelsim#1]
The index.html in this repo is a "please wait" placeholder that implies that some framework "build" needs to take place, e.g. combining/compressing JS files, etc.  

I was hoping a simple `ember-cli` command would build the ready-to-deploy site, but could not figure out the incantation on my own.  Looking for a "build recipe" of some sort...

**Comment by michaelcfine** [comment]
Yeah... see my response to my other email too. I think I wrote my own build
script. webpack didn't exist back then :)

-M
